services:

  database:

    image: mysql:latest
    container_name: database
    restart: always
    volumes:
      - mysql_volume:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: mysqlroot123
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress  
    networks:
      - wordpress_network

  wordpress:

    image: wordpress:latest
    container_name: wordpress
    restart: always
    volumes:
      - wordpress_volume:/var/www/html/
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress  
    networks:
      - wordpress_network
    ports:
      - "80:80"
   
networks:
  wordpress_network:
    driver: bridge

volumes:
  mysql_volume:
  wordpress_volume:
